version: '3.4'
services:
  ui:
    build:
      context: .docker/vue-storefront
      dockerfile: docker/vue-storefront/Dockerfile
      network: host
    env_file: .docker/vue-storefront/docker/vue-storefront/default.env
    environment:
      VS_ENV: dev
    ports:
      - '3000:3000'
    volumes:
      - './.docker/frontend/config.json:/var/www/config/local.json'
      - './.docker/frontend/theme:/var/www/src/themes/default'
      - './.docker/frontend/modules.ts:/var/www/src/modules/client.ts'
      - './:/var/www/src/modules/klevu'
